import type { CollectionConfig } from 'payload'

export const QuizSets: CollectionConfig = {
  slug: 'quiz_sets',
  admin: {
    useAsTitle: 'name',
    defaultColumns: ['name', 'questionCount', 'lastScore', 'isAIGenerated', 'createdAt'],
  },
  access: {
    read: ({ req: { user } }) => {
      if (user) {
        return {
          user: {
            equals: user.id,
          },
        }
      }
      return false
    },
    create: ({ req: { user } }) => !!user,
    update: ({ req: { user } }) => !!user,
    delete: ({ req: { user } }) => !!user,
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
      label: 'Quiz Name',
    },
    {
      name: 'description',
      type: 'textarea',
      label: 'Description',
    },
    {
      name: 'subject',
      type: 'text',
      label: 'Subject/Topic',
    },
    {
      name: 'questionCount',
      type: 'number',
      required: true,
      defaultValue: 0,
      label: 'Number of Questions',
    },
    {
      name: 'questions',
      type: 'json',
      required: true,
      label: 'Quiz Questions',
      // Stores the full question objects as JSON
    },
    {
      name: 'difficulty',
      type: 'select',
      options: [
        { label: 'Easy', value: 'easy' },
        { label: 'Medium', value: 'medium' },
        { label: 'Hard', value: 'hard' },
      ],
      defaultValue: 'medium',
      label: 'Difficulty Level',
    },
    {
      name: 'timeLimit',
      type: 'number',
      label: 'Time Limit (minutes)',
      admin: {
        description: 'Optional time limit for the quiz',
      },
    },
    {
      name: 'lastScore',
      type: 'number',
      min: 0,
      max: 100,
      label: 'Last Score (%)',
      admin: {
        description: 'The score from the last attempt',
      },
    },
    {
      name: 'isAIGenerated',
      type: 'checkbox',
      defaultValue: false,
      label: 'AI Generated Quiz',
      admin: {
        description: 'Whether this quiz was generated by AI or created manually',
      },
    },
    {
      name: 'quizResults',
      type: 'json',
      label: 'Quiz Results',
      admin: {
        description: 'Stores the detailed results from quiz attempts',
      },
    },
    {
      name: 'status',
      type: 'select',
      options: [
        { label: 'Active', value: 'active' },
        { label: 'Completed', value: 'completed' },
        { label: 'Draft', value: 'draft' },
        { label: 'Archived', value: 'archived' },
      ],
      defaultValue: 'active',
      required: true,
      label: 'Status',
    },
    {
      name: 'user',
      type: 'relationship',
      relationTo: 'profiles',
      required: true,
      hasMany: false,
      label: 'Owner',
      admin: {
        condition: () => false, // Hide from admin UI as it's auto-set
      },
    },
    {
      name: 'project',
      type: 'relationship',
      relationTo: 'projects',
      hasMany: false,
      label: 'Associated Project',
      admin: {
        description: 'Optional: Link this quiz to a project',
      },
    },
  ],
  timestamps: true,
}